### ISSUE TITLE
Deploy flask webapp with database

### ISSUE THREAD

**Issue by Gupta-Aryaman** [Gupta-Aryaman/iitm_proj#1]
Hi! I need help with deploying this flask project which is using sqlite as a database currently and using SQLAlchemy as an ORM.
Looking for a no cost solution.

**Comment by AppWebDeveloper1810** [comment]
Hey for deployment you can use Heroku which is a free deployment platform

**Comment by Gupta-Aryaman** [comment]
![image](https://github.com/Gupta-Aryaman/blogger/assets/34962578/f209975f-07d0-4ede-8541-b36013ad9e19)
asks to add credit card, if I add credit card will I be able to deploy for free? It used to be free earlier, not sure about now

**Comment by Gupta-Aryaman** [comment]
Used aws ec2 instance to run my flask server(host="0.0.0.0", port=80), put the terminal in background using screen (NOTE: need to run on port 80 to link it to a domain. Use root privileges to do so) . Then got a custom domain added a new record with my public ipv4 address. Transferred to domain to cloudflare and now it handles everything for me
